language: php

before_install: git submodule init && git submodule --quiet update

before_script:
  - "mysql -e 'create database epgrec_test;'"

php:
  - 5.2
  - 5.3
  - 5.4

script: phpunit --coverage-text -c ./tests/phpunit.xml
